Description: CloudFormation Deployment for resources required to build an MCP server via. Bedrock AgentCore

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC for the SageMaker Domain

  SubnetId1:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet for the SageMaker Domain

  SubnetId2:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet for the SageMaker Domain

  SubnetId3:
      Type: AWS::EC2::Subnet::Id
      Description: Subnet for the SageMaker Domain
  
  SubnetId4:
      Type: AWS::EC2::Subnet::Id
      Description: Subnet for the SageMaker Domain
  
  SubnetId5:
      Type: AWS::EC2::Subnet::Id
      Description: Subnet for the SageMaker Domain
  
  SubnetId6:
      Type: AWS::EC2::Subnet::Id
      Description: Subnet for the SageMaker Domain

Resources:
  #
  # IAM Role for SageMaker
  #
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AdminAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
                
  #
  # SageMaker Domain
  #
  SageMakerDomain:
    Type: AWS::SageMaker::Domain
    Properties:
      DomainName: agentcore-mcp-domain
      AuthMode: IAM
      VpcId: !Ref VpcId
      SubnetIds:
        - !Ref SubnetId1
        - !Ref SubnetId2
        - !Ref SubnetId3
        - !Ref SubnetId4
        - !Ref SubnetId5
        - !Ref SubnetId6
      DefaultUserSettings:
        ExecutionRole: !GetAtt SageMakerExecutionRole.Arn
        JupyterServerAppSettings:
          DefaultResourceSpec:
            InstanceType: system
        KernelGatewayAppSettings:
          DefaultResourceSpec:
            InstanceType: ml.t3.large
      DefaultSpaceSettings:
        ExecutionRole: !GetAtt SageMakerExecutionRole.Arn
        JupyterLabAppSettings:
          DefaultResourceSpec:
            InstanceType: ml.t3.large
  #
  # SageMaker User Profile
  #
  SageMakerUserProfile:
    Type: AWS::SageMaker::UserProfile
    Properties:
      DomainId: !GetAtt SageMakerDomain.DomainId
      UserProfileName: default
      UserSettings: 
        ExecutionRole: !GetAtt SageMakerExecutionRole.Arn
        JupyterLabAppSettings:
          LifecycleConfigArns:
            - !GetAtt MCPAgentCoreRepoLifecycleConfig.StudioLifecycleConfigArn
  #
  # SageMaker Space
  #
  SageMakerSpace:
    Type: AWS::SageMaker::Space
    DependsOn: SageMakerUserProfile
    Properties:
      DomainId: !GetAtt SageMakerDomain.DomainId
      SpaceName: mcp-agentcore
      OwnershipSettings:
        OwnerUserProfileName: default
      SpaceSharingSettings:
        SharingType: Private
      SpaceSettings:
        AppType: JupyterLab
        JupyterLabAppSettings:
          DefaultResourceSpec:
            InstanceType: ml.t3.large
            LifecycleConfigArn: !GetAtt MCPAgentCoreRepoLifecycleConfig.StudioLifecycleConfigArn

  #
  # SageMaker Life Cycle Confir
  #
  MCPAgentCoreRepoLifecycleConfig:
    Type: AWS::SageMaker::StudioLifecycleConfig
    Properties:
      StudioLifecycleConfigName: pyiceberg-repo-clone
      StudioLifecycleConfigAppType: JupyterLab
      StudioLifecycleConfigContent:
        Fn::Base64: |
          #!/bin/bash
          set -eux
  
          REPO_URL="https://github.com/ev2900/MCP_AgentCore"
          TARGET_DIR="/home/sagemaker-user/MCP_AgentCore"
  
          # Ensure git is available (it is on the standard Studio images)
          command -v git
  
          if [ ! -d "${TARGET_DIR}/.git" ]; then
            # Fresh clone
            git clone "${REPO_URL}" "${TARGET_DIR}"
          else
            # If already cloned, just pull latest
            cd "${TARGET_DIR}"
            git pull
          fi
